slam_toolbox:
  ros__parameters:
    use_sim_time: true
    transform_tolerance: 1.0
    queue_size: 100
    base_frame: "base_link"
    odom_frame: "odom"
    map_frame: "map"
    scan_topic: "/scan"
